
sqlquery = ['create table execmeta' ...
'(' ...
    'seq INTEGER PRIMARY KEY,' ...
    'executionId TEXT not null,' ...
    'metadataId TEXT,' ...
    'datapackageId TEXT,' ...
    'user TEXT,' ...
    'subject TEXT,' ...
    'hostId TEXT,' ...
    'startTime TEXT,' ...
    'operatingSystem TEXT,' ...
    'runtime TEXT,' ...
    'softwareApplication TEXT,' ...
    'moduleDependencies TEXT,' ...
    'endTime TEXT,' ...
    'errorMessage TEXT,' ...
    'publishTime TEXT,' ...
    'publishNodeId TEXT,' ...
    'publishId TEXT,' ...
    'console INTEGER,' ...
    'unique(executionId));'];

sqlquery = ['create table filemeta' ...
'(' ...
	'fileId TEXT PRIMARY KEY,' ...
    'executionId TEXT not null,' ...
    'filePath TEXT not null,' ...
    'sha256 TEXT not null,' ...
    'size INTEGER not null,' ...
    'user TEXT not null,' ...
    'modifyTime TEXT not null,' ...
    'createTime TEXT not null,' ...
    'access TEXT not null,' ...
    'format TEXT,' ...
    'archivedFilePath TEXT,' ...
    'foreign key(executionId) references execmeta(executionId),' ...
    'unique(fileId));'];
	

sqlquery = ['create table tags' ...
'(' ...
    'seq INTEGER PRIMARY KEY,' ...
    'executionId TEXT not NULL,' ...
    'tag TEXT not NULL,' ...
    'unique(executionId, tag) ON CONFLICT IGNORE,' ...
    'foreign key (executionId) references execmeta(executionId) on delete cascade' ...
')'];

